### ISSUE TITLE
Is there any sample rosbag to test run!

### ISSUE THREAD

**Issue by ajay1606** [LTU-RAI/Dsp#2]
Hello !

Really thank you so much for sharing very useful repository.
By any chance ! is it possible to share some sample test rosbag file to test the code ?

I have tried to run with my custom bag, but getting following error message. Would you please help me to fix this

![image](https://github.com/LTU-RAI/Dsp/assets/29722843/946119e8-f224-491b-9136-ce0fdfed2149)

Appreciate any response. 

Regards,
Ajay

**Comment by grammers** [comment]
[https://res-h3.public.cdn.office.net/assets/mail/file-icon/png/generic_16x16.png]dsp_demp.bag<https://1drv.ms/u/s!At9PoZmhibVOitshZe2DsiZEXHYBIA>

Hello!
Here is a small example.
Unfortunately is the tf in it a bit odd. The Odom frame is in this case 'shafter_world' and the base_link frame is 'base_link_shafter'.
I also attached a launch file that should work with this data. Hope this helps.

Regards,
Samuel

________________________________
From: Ajay ***@***.***>
Sent: Sunday, January 21, 2024 11:58 PM
To: LTU-RAI/Dsp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [LTU-RAI/Dsp] Is there any sample rosbag to test run! (Issue #2)


Hello !

Really thank you so much for sharing very useful repository.
By any chance ! is it possible to share some sample test rosbag file to test the code ?

Appreciate any response.

Regards,
Ajay

**Comment by ajay1606** [comment]
@grammers , Thank you so much for your response ! Unfortunately link you shared not opening, would you please share it again.

**Comment by grammers** [comment]
With this launch: https://drive.google.com/file/d/1jwNcQG0UOaWuHm4qjK8OhR1vQyGsHFnH/view?usp=sharing
And this bag: https://drive.google.com/file/d/1WyqQqnZaze4t7kvjTKv0fsFITi9sENJz/view?usp=sharing
Is octomap working.

The tf tree is this. the point cloud is on Velodyne. This tree is larger than needed for this example and a bit of a mess.
![frames](https://github.com/LTU-RAI/Dsp/assets/15670861/dca2fe16-a083-42b4-b93c-13ef033be45f)

Your tree is missing the link from base_link to Velodyne.

**Comment by ajay1606** [comment]
@grammers Thank you so much for sharing demo files and i have configured my `tf` accordingly. 
Now am able to get `octomap_full` publishing correctly.

And in my case, `velodyne` sensor data already moved to `base_link`, hence there are no any static_transformation included. 
With above tree, i am able to get `octomap_full` with my data as well.

But with the both of data bag, i am able to see following in my terminal. Does it normal functioning !
![image](https://github.com/LTU-RAI/Dsp/assets/29722843/116d9c3d-5058-4d37-b857-e15e85fe3653)

Are there any visualization supported ? Is there any way i can visualize `goal_pose` and `planned trajectory` !!
